services:

#Maria DB
  mariadb:
    container_name: mariadb
    image: mariadb:11.4.2
    environment: 
      - MYSQL_ROOT_PASSWORD=spark
      - MYSQL_USER=spark
      - MYSQL_PASSWORD=spark
      - MYSQL_DATABASE=spark_de
    ports: 
      - '3306:3306'      

#Kafka Service
  kafka:
    image: 'bitnami/kafka:3.6'
    container_name: kafka-broker

    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1001
      
      - KAFKA_CFG_NODE_ID=1001
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=CLIENT://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:29092,EXTERNAL://localhost:9092
      #Identify all other controllers in the cluster
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@127.0.0.1:9093
    
    ports:
      - '9092:9092'
      
#Redis
  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    
    ports: 
      - '6379:6379'
      

